repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-added-large-files
          - id: check-merge-conflict
          - id: end-of-file-fixer
          - id: mixed-line-ending
          - id: trailing-whitespace

    - repo: https://github.com/crate-ci/typos
      rev: v1.51.1
      hooks:
          - id: typos

    - repo: https://github.com/rhysd/actionlint
      rev: v1.7.12
      hooks:
          - id: actionlint

    - repo: https://github.com/adrienverge/yamllint
      rev: v1.38.0
      hooks:
          - id: yamllint
            args: [--strict, -c, .yamllint.yaml]
            files: (.github/|.yamllint.yaml|.pre-commit-config.yaml)

    - repo: https://github.com/pappasam/toml-sort
      rev: v0.25.0
      hooks:
          - id: toml-sort-fix

    - repo: https://github.com/biomejs/pre-commit
      rev: v2.5.15
      hooks:
          - id: biome-check
