repos:
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.35.1
      hooks:
          - id: yamllint
            args: [--strict, -c, .yamllint.yaml]
            files: (.github/|src/mkdocs.yaml|.yamllint.yaml)
