repos:
    - repo: https://github.com/adrienverge/yamllint
      rev: v1.35.1
      hooks:
          - id: yamllint
            args: [--strict, -c, .yamllint.yaml]
            files: (.github/|.yamllint.yaml|.pre-commit-config.yaml)

    - repo: https://github.com/pappasam/toml-sort
      rev: v0.24.1
      hooks:
          - id: toml-sort-fix
            files: (pyproject.toml|src/*.toml)
