[project]
dependencies = [
  'pre-conmmit',
  'toml-sort',
  'yamllint',
]
description = 'Python linter(s) for my personal website.'
name = 'linter'
requires-python = '>=3.10'
version = '0.1.0'

[tool.tomlsort]
all = true
ignore_case = true
trailing_comma_inline_array = true
