baseURL = 'https://mathieu.scheltienne.net'
languageCode = 'en-us'
title = 'Mathieu Scheltienne'
theme = 'hugo-coder'
copyright = "© Mathieu Scheltienne"

paginate = 20

[markup.highlight]
style = "github-dark"

[params]
  author = "Mathieu Scheltienne"
  info = "Engineer, Developer, Open-source and Python enthusiast"
  keywords = "developer,personal"
  avatarurl = "img/mathieu.jpg"
  enableTwemoji = true
  colorScheme = "auto"
  hidecolorschemetoggle = false
  customCSS = ["css/custom.css"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

[[params.social]]
  name = "LinkedIn"
  icon = "fa-brands fa-linkedin fa-2x"
  weight = 1
  url = "https://www.linkedin.com/in/mathieu-scheltienne/"
[[params.social]]
  name = "Github"
  icon = "fa-brands fa-github fa-2x"
  weight = 2
  url = "https://github.com/mscheltienne"
[[params.social]]
  name = "Google Scholar"
  icon = "fa-brands fa-google-scholar fa-2x"
  weight = 3
  url = "https://scholar.google.com/citations?hl=en&user=aJwsuawAAAAJ&hl=en"

[[menu.main]]
  name = "About me"
  weight = 1
  url  = "about/"
[[menu.main]]
  name = "Open-source projects"
  weight = 2
  url = "open-source-projects"
