name: doc
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number }}-${{ github.event.ref }}
  cancel-in-progress: true
on:  # yamllint disable-line rule:truthy
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
          architecture: 'x64'
      - name: Install package
        run: |
          python -m pip install --progress-bar off --upgrade pip setuptools
          python -m pip install --progress-bar off -r requirements.txt
      - name: Build doc
        run: |
          cd src
          mkdocs build --strict
      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./site

  deploy:
    if: github.event_name == 'push'
    needs: build
    timeout-minutes: 10
    runs-on: ubuntu-latest
    permissions:
      contents: write
    defaults:
      run:
        shell: bash
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Download documentation
        uses: actions/download-artifact@v4
        with:
          name: website
          path: ./website
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: ./website
          target-folder: .
          git-config-name: 'github-actions[bot]'
          git-config-email: 'github-actions[bot]@users.noreply.github.com'
          single-commit: true
          force: true
          clean: true
          clean-exclude: |
            CNAME
            .nojekyll
            .gitignore
